HaikuArchives/CapitalBe

src/ReconcileWindow.cpp
I've set a minimum size limit on the reconcile limit to be the same as the default height and width of the window and increased the default width to 650 as it seems to look better at least in my opinion.
Fixes #18
=> Set a minimum size limit on the reconcile window

src/AccountSettingsWindow.cpp, src/BudgetReport.cpp
Fixes #4
The Account Settings window would crash if the account has not been
created yet and the checkbox (checked by default) was unchecked.
Fixes #25
The Reports window would crash if the Subtotal menu was set to anything
but the default None that would result in a multi-column output.
=> Fix crashes in the Account Settings window and the Reports window

ToDO_Spanish, locales/en.catkeys, src/CategoryBox.cpp, src/CppSQLite3.cpp, src/CppSQLite3.h, src/Database.cpp, src/LICENSE, src/Locale.cpp, src/MainWindow.cpp
This PR fixes a problem with escaped characters in transaction memos. Fixes #7 
I've also included an updated version of the CppSQLite3 library from https://github.com/neosmart/CppSQLite. The previous version caused some non-fatal warnings during the build process. I haven't seen any issues with this change.
In addition, some missing strings where added for translation, as mentioned in `ToDo_Spanish`. Maybe this program can be added to Polyglot at some point for additional translations? 
Note that the bug report message (`CapitalBe has run into a bug`)  is translatable, but not the actual bug report that will be saved and possibly sent to a developer.
=> Issue #7: Memo bug

locales/en.catkeys, src/Account.cpp, src/AccountSettingsWindow.cpp, src/Database.cpp, src/MainWindow.cpp, src/QuickTrackerItem.cpp
This PR fixes some issues where custom currency settings where lost when closing the app. In addition, QuickTracker will show the total balance for each of the currencies, instead of adding them all.
- Custom currency settings are correctly saved
- Fixes #50 
- QuickTracker lists the balance per currency, not all combined
- Replaced custom window centering with CenterIn()
I'm not sure what the best way to list the QuickTracker information is, I opted for "Balance" followed by the currency symbol, but maybe there's another way that is more intuitive?
=> Improved support for multiple currencies

locales/en.catkeys, src/CheckView.cpp, src/CheckView.h, src/MainWindow.cpp, src/RegisterView.cpp, src/ScheduleListWindow.cpp, src/TransferWindow.cpp
This fixes #51 , by disabling the fields for entering transactions if the account is closed.
Double-click on a transaction for editing will show a warning message.
=> Disable editing on closed accounts

locales/en.catkeys, src/AccountSettingsWindow.cpp, src/CategoryWindow.cpp, src/MainWindow.cpp, src/ReconcileWindow.cpp, src/ScheduledTransItem.cpp, src/SplitView.cpp, src/TransactionItem.cpp
* Sentence casing.
* When creating/editing an Account or Category, it's not needed to label the text control e.g. "New category name:", because the window title already says we're editing a category. This saves space, too.
* Put variables like %%FILENAME%% etc. in single quotes. Reads better when there are spaces in those names.
* Replaced one left "e-mail support" to "go report a bug".
* Update en.catkeys
=> Fine tuning some GUI strings

locales/en.catkeys, src/AccountListItem.cpp, src/AccountSettingsWindow.cpp, src/Budget.cpp, src/BudgetReport.cpp, src/BudgetWindow.cpp, src/CategoryBox.cpp, src/CheckNumBox.cpp, src/CurrencyBox.cpp, src/Database.cpp, src/DateBox.cpp, src/HelpButton.cpp, src/MainWindow.cpp, src/PayeeBox.cpp, src/QuickTrackerItem.cpp, src/ReconcileWindow.cpp, src/ReportWindow.cpp, src/ScheduleAddWindow.cpp, src/SplitView.cpp, src/TransactionEditWindow.cpp, src/TransactionItem.cpp, src/TransferWindow.cpp
- Clean up the language strings. I'm sure there are more that can be done, but this should reduce repeated terms a bit.
- Remove "." after dialog box titles.
=> Improve language strings

locales/en.catkeys, src/AccountSettingsWindow.cpp, src/AccountSettingsWindow.h, src/BudgetWindow.cpp, src/BudgetWindow.h, src/CategoryWindow.cpp, src/CheckView.cpp, src/CheckView.h, src/MainWindow.cpp, src/PrefWindow.cpp, src/PrefWindow.h, src/RegisterView.cpp, src/ReportWindow.cpp, src/ScheduleAddWindow.cpp, src/ScheduleListWindow.cpp, src/SplitView.cpp, src/TransactionEditWindow.cpp, src/TransferWindow.cpp
There are a few more to follow. Don't merge yet...
=> More layout tweaks

src/AccountListItem.cpp, src/Preferences.cpp, src/Preferences.h, src/ScheduledTransItem.cpp, src/TransactionItem.cpp
* Use B_LIST_SELECTED_ITEM_TEXT_COLOR when drawing text of a selected item.
* When calling GetMutedTint() to draw items of a closed account, it's not OK to check always against B_PANEL_BACKGROUND_COLOR to determine if to lighten or darken. We need to compare to the background colour the text will be drawn on or - vice-versa - the text colour that will be drawn on the background colour.
Therefore, we call GetMutedTint() with the colour we want it have compared to.
* Added TODO to use Haiku's IsDark() once Haiku Beta 5 is out.
* Replace SetHighUIColor() with SetHighColor(), because the former can only deal with the system color_which constants, not rgb_color.
* Fixed "No memo" not being drawn tinted in closed accounts.
=> Fix the coloring for different system themes

src/Preferences.cpp, src/Preferences.h, src/TransactionItem.cpp
* Lighten/darken every other transaction item for better orientation. Reuses GetMutedTint() with a new type CB_ALT_ROW.
* Fix a slightly off drawing of the selected stroked frame. Always draw the bottom line, also for selected items. Before, horizontal lines were a pixel short at the right. Fixed after removing the "r.right--"...
Screenshots:
Before:
After:
=> Show alternate colours in Transaction view

locales/en.catkeys, src/Account.cpp, src/Account.h, src/AccountSettingsWindow.cpp, src/BudgetWindow.cpp, src/BudgetWindow.h, src/CBLocale.h, src/Database.cpp, src/Database.h, src/Locale.cpp, src/PrefWindow.cpp, src/PrefWindow.h, src/QuickTrackerItem.cpp
New PR, the long country list has been removed. Fixes #8.
- The monetary formatting from the Haiku locale kit is used by default.
- A custom currency symbol can be set, but the number itself is still formatted using the locale kit
- Remove unused code and methods
- Change some of the SQL queries to uppercase for easier reading
=> Use locale kit for number formatting

locales/en.catkeys, src/BudgetReport.cpp, src/Database.cpp, src/Database.h, src/MainWindow.cpp, src/MainWindow.h, src/NetWorthReport.cpp, src/QuickTrackerItem.cpp, src/ScheduleAddWindow.cpp, src/ScheduleListWindow.cpp
Fixing some more bugs and crashes.
Also adding a warning when deleting accounts with scheduled transactions, and making sure schedules are run when created and every 30 seconds (fixes #74 ). [edited]
- Remove scheduled transactions when account is deleted
- Run scheduled transactions when added and every 30 seconds [edited]
- Fix crash in report window
- Show warning about scheduled transactions
- Set Scheduled win min width
- Fixes #78 - QuickTracker
=> More bug fixes

helpfiles/en/Main Window.txt, src/DateBox.cpp
"+" used to increase the day. There was no "-" to decrease, because that may be used as date delimiter(?).
I think this change makes the shortcuts more intuitive:
* CursorUp/Down : in/decrease day
* SHIFT+CursorUp/Down : in/decrease month
* PageUp/Down : in/decrease year
In/decreasing the year is only seldomly used, so it's fine to have it on a less commonly used shortcut. In/decreasing the day/month is handy much more often and is therefore on the most familiar cursor keys.
Updated help file accordingly.
This change also reduces code duplication.
=> DateBox filter: Improved shortcuts

locales/en.catkeys, src/ScheduleListWindow.cpp
* The memo of every scheduled transaction usually provides important information. No reason not showing it.
* Slightly wider columns, esp. for the amount, to avoid truncation.
* Fixed typo in column label.
* Updated en.catkeys
=> Scheduled transaction: Add "Memo" column

src/Database.cpp, src/ScheduleListWindow.cpp, src/SplitView.cpp
Fixes #75 by deescaping the memo. Also fixes a similar issue with memos in split transactions.
=> Deescape memo in split view and scheduled list

locales/en.catkeys, src/Import.cpp
Is this enough to close #5 ?
It is just a basic check if anything was imported. QIF-files are simple text files, and the import script runs through each line looking for something to import. If nothing is found, it now returns `false` and displays a message.
Attached is a small QIF file for testing.
[1_qif_example.qif.txt](https://github.com/user-attachments/files/15878515/1_qif_example.qif.txt)
=> Show warning on failed QIF import

src/AccountListItem.cpp, src/MainWindow.cpp, src/RegisterView.cpp, src/RegisterView.h, src/TransactionItem.cpp
I first wanted to implent a BSplitView, but then came to the conclusion that there's no need for the user to decide on the width of the left sidebar. Just make it as wide as the longest account name, or make it wide enough to show "Balance: $99,999,999,00" in the QuickTracker.
=> Layout tweaks

Makefile, src/CategoryButton.cpp, src/CategoryButton.h, src/CategoryWindow.cpp, src/CheckView.cpp, src/Database.h, src/ReconcileWindow.cpp, src/ReportWindow.cpp, src/ScheduleAddWindow.cpp, src/SplitView.cpp, src/SplitView.h, src/TransferWindow.cpp
* Add a button besides the category text box that opens a popup menu showing all categories in "Income" and "Spending" submenus. Choosing a category puts it in the text box. Choosing "Edit categories..." opens the same Categories window also available from the MainWindow.
* Introduce a category_type enum to distinguish SPENDING and INCOME. Test explicitely against those and don't assume INCOME if it's not SPENDING. In future we may have other category types, e.g. TRANSFER which only gets set by CapitalBe, not the user.
* To make the connection between category box and its button a tiny bit more visible "merge" their widgets borders by having a -2 spacing.
* Do the same for the date box + button everywhere. This entails using a separate BStringView for their labels, because putting box and …
=> Adding Category selection button

src/ScheduleListWindow.cpp, src/ScheduledExecutor.cpp
This PR fixes #86.
* Scheduled transactions will not run on closed accounts
* Closed accounts will not show up in the list of scheduled transactions either, but reopening the account will bring them back.
=> Ignore scheduled transactions on closed accounts

src/Account.cpp, src/BudgetReport.cpp, src/BudgetWindow.cpp, src/CashFlowReport.cpp, src/CategoryWindow.cpp, src/CheckView.cpp, src/Database.cpp, src/Database.h, src/Import.cpp, src/PrefWindow.cpp, src/QuickTrackerItem.cpp, src/ReportWindow.cpp, src/ScheduleListWindow.cpp, src/SplitView.cpp, src/TransactionReport.cpp, src/TransactionView.cpp
This is an attempt to prepare for possible future DB changes (e.g. when using system locale for dates and currencies) without the need for a conversion tool. Users upgrading from previous versions (or even before versioning was implemented) will automatically have any DB changes applied.
I'm not sure if my logic is correct or if there is a better way to implement this, any feedback appreciated. It seems to work with databases from CapitalBe 1.1.0 from HaikuDepot. Maybe an automatic backup of the current database would be a good idea in order to protect user data.
Each time a release requires database changes, the version number in `Database.cpp` is incremented, and the required logic (changing tables and migrating data) must be added as a new if-clause in `Database::ApplyMigrations()`. …
=> Add database versioning

src/AutoTextControl.cpp, src/AutoTextControl.h, src/CategoryBox.cpp, src/CategoryButton.cpp
* Before there was a CategoryButton that would insert a category in the CategoryBox, there was only the CategoryBox' AutoTextControl() that did autocomplete and informed the SplitView that the category was edited.
The CategoryButton simply inserting the new category in the text control isn't enough. It has to notify the SplitView of that, so it can update a changed category in the the list of split transactions at the bottom of the window.
After introducing GetMessenger() to the AutoTextControlFilter we can now send a M_SPLIT_CATEGORY_CHANGED to the CategoryBox's parent, i.e. the SplitView.
* Split transactions get the category "Split transaction" by the app. Ignore those when checking against existing user-created categories. It won't be found there and would get added as new …
=> Fix split category update

src/Database.cpp, src/SplitView.cpp, src/SplitViewFilter.cpp, src/TransactionItem.cpp
* When editing a split transaction, the original transaction is deleted from the database, and new transactions are created for each split item with the same transaction ID. The ID wasn't correctly set, causing the original transaction to be deleted, and the new transactions to be added to the  transaction with ID 0.
* Deleting an account would not remove associated transactions from the `transactionlist` table.
* Converted some queries to use BString::SetToFormat
=> Fix DB errors with split transactions

src/CategoryBox.cpp, src/CategoryButton.cpp, src/CategoryWindow.cpp, src/Database.cpp, src/Database.h, src/SplitView.cpp
The user mustn't set "internal categories" (Income, Spending, Split, Transfer, Uncategorized). Therefore they mustn't show up in the "Categories" window, or the menu of the category button, or when doing autocomplete.
The new function IsInternalCategory() checks if a category is "internal".
=> Don't let the user set internal categories

locales/en.catkeys, src/Account.cpp, src/CategoryBox.cpp, src/CheckView.cpp, src/Database.cpp, src/ScheduleAddWindow.cpp, src/ScheduledTransItem.cpp, src/SplitView.cpp, src/SplitViewFilter.cpp, src/TransactionItem.cpp
* Replace "Split transaction" with "Split"
* Restore orginal category when un-splitting
* Update catkeys
* Don't validate 'Split' category for split transactions
* Remove 'Split' as shortcut when entering new transaction
=> Bug fixes for split transactions

src/CheckView.cpp
Fixes issue #103 . The database fields are set to VARCHAR(63), but AFAIK, SQLite does not enforce this, and any length is possible.
I've set the limit to 63 characters, mostly because very long strings will look strange and/or break the layout. Maybe there's a good way to handle long strings, like adding a tool tip on hover or something like that?
=> Increase memo and payee character limit

src/CategoryBox.cpp, src/PayeeBox.cpp
If the user enters a letter that has the Autocomplete*() function return empty, because the string doesn't match anymore, send the M_*_AUTOCOMPLETE BMessage with the entire text control text. Including that non-matching letter.
=> Fix auto-complete for Payee and Category

src/SplitView.cpp
Only validate split items if the SplitView is actually shown, which makes the transaction a "split-transaction". Only then the original amount cannot be different that the split-total.
Fixes #100
=> Fix editing amount of a transaction

src/CategoryBox.cpp
=> Don't capitalize categories
